name: pendulum
description: A dynamic, Stream-based API for job scheduling in Dart, capable of processing on different triggers.
version: 0.1.1
homepage: https://www.example.com

environment:
  sdk: '>=2.1.0 <3.0.0'

# dependencies:

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0
